# Config for plugin
update_checker: true




telegram:
    enabled: false
    token: TELEGRAM_TOKEN
    chat_ids: []
    events:
        onJoin: true
        onQuit: true
    message_formats:
        onJoin: '{username}, joined the server!'
        onQuit: '{username}, left the server!'