# Config for plugin
update_checker: true

telegram:
    enabled: false
    token: TELEGRAM_TOKEN
    chat_ids: []
    events:
        PlayerJoinEvent: false
        PlayerQuitEvent: false
        PlayerDeathEvent: false
    message_formats:
        PlayerJoinEvent: '{name}, joined the server!'
        PlayerQuitEvent: '{name}, left the server!'
        PlayerDeathEvent: '{name} died at x: {death_x} y: {death_y} z: {death_z} {death_cause}'