# Config for plugin
update_checker: true

# ignores events for players and entities (for all notifiers)
ignored_players:
    - nombrekeff

# AVAILABLE NOTIFIERS
discord:
    enabled: false
    token: TOKEN
    events:
        PlayerJoinEvent: 
            format: '{name}, joined the server!'
        PlayerQuitEvent: 
            format: '{name}, left the server!'
        PlayerDeathEvent: 
            format: '{name} died in {world}, at x: {death_x} y: {death_y} z: {death_z} {death_cause}'
            
webhook:
    enabled: false
    enpoint: https://webhook.site/d50cdcbe-6d53-4a23-8d67-eec726235f26
    method: POST
    # ignores events for players and entities (for this notifiers)
    ignored_players: [] 
    events:
        PlayerJoinEvent: 
            format: '{name}, joined the server!'
        PlayerQuitEvent: 
            format: '{name}, left the server!'
        PlayerDeathEvent: 
            format: '{name} died in {world}, at x: {death_x} y: {death_y} z: {death_z} {death_cause}'

telegram:
    enabled: false
    token: TELEGRAM_TOKEN
    chat_ids: []
    # ignores events for players and entities (for this notifiers)
    ignored_players: []
    events:
        PlayerJoinEvent: 
            format: '{name}, joined the server!'
        PlayerQuitEvent: 
            format: '{name}, left the server!'
        PlayerDeathEvent: 
            format: '{name} died in {world}, at x: {death_x} y: {death_y} z: {death_z} {death_cause}'