main: dev.keff.spigot.yallnotified.App
name: YallNotified
version: 0.0.1-beta3

commands:
    yn:
       description: YallNotified utility commands
       usage: /yn <ignore|unignore> <player> [notifier]